### ISSUE TITLE
Camera support plate could be wider

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#11]
The spacer piece could be wider to provide the camera better stability:

![image](https://user-images.githubusercontent.com/5435954/204078920-888ec582-eab0-4583-aae7-f5736b0f1e38.png)

**Comment by Gautier30** [comment]
I enlarged the camera spacer. Please let me know if you find any issue
![image](https://user-images.githubusercontent.com/75580818/204290585-8c176f82-a0e3-4e0b-83dc-9324e231b66b.png)
