### ISSUE TITLE
Simplify battery holder

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#12]
Currently the battery holder assembly and the way it attaches seem quite complex. Maybe we can simplify it.

I suggest something like 2 guide pins to locate the assembly and 1 screw to fasten it. The screw can go thorugh the whole thing and also connect the computer mounting plate to everything. Something like this (red is added geometyr, blue is the screw)

![image](https://user-images.githubusercontent.com/5435954/204079039-05d5a821-eb3b-4809-b016-7d50851a4521.png)

**Comment by Gautier30** [comment]
I tried to improve following your suggestions. Fastening the battery holder now also fixes the computer plate. I made 4 guide pins but let me know if you think it's overkill. 
![image](https://user-images.githubusercontent.com/75580818/204289867-38f5a02c-a42c-474e-a1bc-65fca3967fb3.png)
![image](https://user-images.githubusercontent.com/75580818/204289924-493a33f0-45c7-4f7d-a641-ec14617193b8.png)
