### ISSUE TITLE
Balls can get stuck in the frame

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#14]
Be cautious because balls can get stuck in the frame. If you handle multiple balls, it is a fault.

![image](https://user-images.githubusercontent.com/5435954/204079127-13836b4a-14f3-4ae5-b53f-cf335b710f49.png)

**Comment by Gautier30** [comment]
I've added some kind of fenders to prevent balls from getting stuck. I might extend them a little to be  even safer...

![image](https://user-images.githubusercontent.com/75580818/204321386-f90de38c-6be3-47cd-a938-35b978cf53c8.png)
