### ISSUE TITLE
Dont forget dogbones

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#18]
Try not to forget dog bones in internal corners. Some examples:

![image](https://user-images.githubusercontent.com/5435954/204079497-c8241d25-1e8a-4ba6-ac2a-cbbe1e7cf53d.png)

![image](https://user-images.githubusercontent.com/5435954/204079506-fb61e27f-794b-41df-b246-0858b6205cd8.png)

**Comment by Akustav** [comment]
Still an issue on the camera legs

**Comment by Akustav** [comment]
Dogbones are missing here as well: 
![image](https://user-images.githubusercontent.com/5435954/205482222-9a6c26e2-df06-462e-be8a-99e9f1ae9d8b.png)

**Comment by Gautier30** [comment]
I've added dog bones everywhere they might be needed.

![image](https://user-images.githubusercontent.com/75580818/205666460-d83e316e-2f6c-48b7-a47d-73496f9ae4b4.png)
![image](https://user-images.githubusercontent.com/75580818/205669791-6f535cea-01c4-4f92-8aff-1e8b15bb573c.png)
![image](https://user-images.githubusercontent.com/75580818/205669821-dfdfcc41-454a-40f8-b22e-ad849e5a0b0f.png)
![image](https://user-images.githubusercontent.com/75580818/205670758-fba20a4c-87b0-46ff-a2c4-8c8396a93e5c.png)
