### ISSUE TITLE
Can screw heads make it idfficult to use the XT-60 sockets

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#19]
Can screw head size interfere with the sockets?

![image](https://user-images.githubusercontent.com/5435954/204079563-bd7afe16-8409-47b8-9602-1e237e084ecc.png)

**Comment by ReikoR** [comment]
Connector nut thread size is M2.5, so it should be fine. Typical M2.5 screw head diameter should be 4.5mm.
