### ISSUE TITLE
Camera FOV visualisation missing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#20]
Currently there is no accurate FOV visualization on the model for the camera. IT would help with validating the camera location.

**Comment by Gautier30** [comment]
I added some centerlines in a sketch within the camera support part. I tried doing the same on the camera model itself but I had a weird bug with the sketches on the robot assembly. This solution should give an idea of the cam's POV...
Please let me know if it's not satisfactory. 

![image](https://user-images.githubusercontent.com/75580818/204297684-2867b59a-cd08-49aa-8690-def397bcfbe0.png)
