### ISSUE TITLE
Electronics inside the chassis missing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#21]
There currently is no representation of the voltage converter and the mainboard in the chassis

**Comment by Gautier30** [comment]
The PCB isn't ready yet so I don't have its CAD file. I made a "kinda PCB" part which will be placed above the voltage regulator with standoffs as such:

![image](https://user-images.githubusercontent.com/75580818/205692568-33d55750-f432-4e08-b01a-7303783f559d.png)

Our electronics guy is working on the PCB so it has exactly the same footprint as this dummy one.
