### ISSUE TITLE
Beef up sidewall fastening

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-robodendron#7]
I suggest making the sidewalls of the robot stronger. They will get hit many times during game-play and should not break:

![image](https://user-images.githubusercontent.com/5435954/204078602-d1208091-a05f-4a89-8520-419cd6044026.png)

**Comment by Gautier30** [comment]
I made the side walls sturdier by adding some material, please let me know what you think about them now.
![image](https://user-images.githubusercontent.com/75580818/204290368-97961d13-a85a-4442-8aed-bacdd3f164c8.png)
